name: dztest
favicon: null
layout_spectrum: 0.9872
typography_spectrum: 0.48379
title: dztest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#52565f'
    - '#52aac9'
    - '#ffffff'
    - '#54d2fa'
    - '#cbcccf'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
