name: dztest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25544
title: dztest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d7e1'
    - '#b4c2d5'
    - '#88a9c5'
    - '#6887a0'
    - '#475e70'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.4306232032831758
  rhythmicContrast: 0.5
purpose: []
